apiVersion: apps/v1
kind: Deployment
metadata:
  name: DOFExam-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: DOFExam
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: DOFExam
    spec:
      containers:
      - name: app-cont
        image: ktsankow/dofexam:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: DOFExam-svc
  labels:
    app: DOFExam
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: DOFExam
